from .crud_area import area
from .crud_control_point import control_point
from .crud_customer import customer
from .crud_headquarter import headquarter
from .crud_service import service
from .crud_treatments import treatments
from .crud_user import user
from .crud_sanity_plan import sanity_plan
from .crud_document import document
