"""added name to docs nullable

Revision ID: 4586a1c2b43b
Revises: d693ed86e8ef
Create Date: 2023-05-25 19:43:01.438784

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4586a1c2b43b'
down_revision = 'd693ed86e8ef'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document', sa.Column('name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('document', 'name')
    # ### end Alembic commands ###
