"""Added treatments, mant2many services

Revision ID: 4a493fcbe426
Revises: d079ed54f2a9
Create Date: 2023-05-17 19:13:02.070659

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a493fcbe426'
down_revision = 'd079ed54f2a9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('treatment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('cost', sa.Integer(), nullable=False),
    sa.Column('frequency', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_treatment_id'), 'treatment', ['id'], unique=False)
    op.create_index(op.f('ix_treatment_name'), 'treatment', ['name'], unique=False)
    op.create_table('servicetreatment',
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('treatment_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('observations', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['service_id'], ['service.id'], ),
    sa.ForeignKeyConstraint(['treatment_id'], ['treatment.id'], ),
    sa.PrimaryKeyConstraint('service_id', 'treatment_id')
    )
    op.add_column('area', sa.Column('incidence', sa.Boolean(), nullable=False))
    op.add_column('area', sa.Column('activity_level', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('area', 'activity_level')
    op.drop_column('area', 'incidence')
    op.drop_table('servicetreatment')
    op.drop_index(op.f('ix_treatment_name'), table_name='treatment')
    op.drop_index(op.f('ix_treatment_id'), table_name='treatment')
    op.drop_table('treatment')
    # ### end Alembic commands ###
