"""Added status to service

Revision ID: 515e874ef788
Revises: a108a6356808
Create Date: 2023-05-23 08:52:31.468987

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '515e874ef788'
down_revision = 'a108a6356808'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service', sa.Column('status', sa.String(), nullable=True))
    op.drop_index('ix_service_service_type', table_name='service')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_service_service_type', 'service', ['service_type'], unique=False)
    op.drop_column('service', 'status')
    # ### end Alembic commands ###
