"""Added customer, headquarter and area tables

Revision ID: 80cf82d754b6
Revises: 7fd1fcec98d9
Create Date: 2023-05-08 09:14:42.414699

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80cf82d754b6'
down_revision = '7fd1fcec98d9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.String(), nullable=False),
    sa.Column('customer_type', sa.String(), nullable=False),
    sa.Column('commercial_name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customer_document_id'), 'customer', ['document_id'], unique=False)
    op.create_index(op.f('ix_customer_id'), 'customer', ['id'], unique=False)
    op.create_table('headquarter',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('neighborhood', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_headquarter_id'), 'headquarter', ['id'], unique=False)
    op.create_table('area',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('estimated_time', sa.String(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('headquarter_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.ForeignKeyConstraint(['headquarter_id'], ['headquarter.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_area_id'), 'area', ['id'], unique=False)
    op.create_index(op.f('ix_area_name'), 'area', ['name'], unique=False)
    op.add_column('user', sa.Column('document_id', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('is_technician', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('is_customer', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('color', sa.String(), nullable=True))
    op.create_index(op.f('ix_user_document_id'), 'user', ['document_id'], unique=False)
    op.create_unique_constraint(None, 'user', ['color'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_index(op.f('ix_user_document_id'), table_name='user')
    op.drop_column('user', 'color')
    op.drop_column('user', 'is_customer')
    op.drop_column('user', 'is_technician')
    op.drop_column('user', 'document_id')
    op.drop_index(op.f('ix_area_name'), table_name='area')
    op.drop_index(op.f('ix_area_id'), table_name='area')
    op.drop_table('area')
    op.drop_index(op.f('ix_headquarter_id'), table_name='headquarter')
    op.drop_table('headquarter')
    op.drop_index(op.f('ix_customer_id'), table_name='customer')
    op.drop_index(op.f('ix_customer_document_id'), table_name='customer')
    op.drop_table('customer')
    # ### end Alembic commands ###
