"""Updated observations in services

Revision ID: a108a6356808
Revises: 1493c9654cb1
Create Date: 2023-05-20 20:49:06.086216

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a108a6356808'
down_revision = '1493c9654cb1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('service', 'observations',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_index('ix_service_observations', table_name='service')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_service_observations', 'service', ['observations'], unique=False)
    op.alter_column('service', 'observations',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
