"""Added sanityplan and controlpoints

Revision ID: b6930891251e
Revises: 4a493fcbe426
Create Date: 2023-05-20 19:55:34.658850

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6930891251e'
down_revision = '4a493fcbe426'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sanityplan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('visits_qty', sa.Integer(), nullable=False),
    sa.Column('frequency', sa.String(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sanityplan_id'), 'sanityplan', ['id'], unique=False)
    op.create_table('controlpoint',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('observations', sa.String(), nullable=False),
    sa.Column('area_id', sa.Integer(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('headquarter_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['area_id'], ['area.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.ForeignKeyConstraint(['headquarter_id'], ['headquarter.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_controlpoint_id'), 'controlpoint', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_controlpoint_id'), table_name='controlpoint')
    op.drop_table('controlpoint')
    op.drop_index(op.f('ix_sanityplan_id'), table_name='sanityplan')
    op.drop_table('sanityplan')
    # ### end Alembic commands ###
