"""Updated url to docs nullable

Revision ID: d693ed86e8ef
Revises: bfd83a562caf
Create Date: 2023-05-25 19:41:37.187448

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd693ed86e8ef'
down_revision = 'bfd83a562caf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document', sa.Column('url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('document', 'url')
    # ### end Alembic commands ###
