from .area import Area
from .associations.service_treatment import ServiceTreatment
from .associations.service_user import ServiceUser
from .customer import Customer
from .headquarter import Headquarter
from .invoice import Invoice
from .service import Service
from .treatment import Treatment
from .user import User
